<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">

<plist version="1.0">
<dict>
    <key>name</key>
    <string>Salt</string>
    <key>scopeName</key>
    <string>source.salt</string>
    <key>fileTypes</key>
    <array>
        <string>salt</string>
    </array>
    <key>patterns</key>
    <array>
    <dict>
        <key>match</key>
        <string>(#define)\s+([a-zA-Z_][a-zA-Z0-9_]*)\s+(.+)$</string>
        <key>captures</key>
        <dict>
            <key>1</key>
            <dict>
                <key>name</key>
                <string>keyword.control.directive.define.salt</string>
            </dict>
            <key>2</key>
            <dict>
                <key>name</key>
                <string>constant.other.define.salt</string>
            </dict>
            <key>3</key>
            <dict>
                <key>name</key>
                <string>meta.preprocessor.value.salt</string>
            </dict>
        </dict>
    </dict>

    <dict>
        <key>match</key>
        <string>\b(return|if|else|while|break|continue|void|struct)\b</string>
        <key>name</key>
        <string>keyword.control.salt</string>
    </dict>

    <dict>
        <key>match</key>
        <string>@[a-zA-Z]+</string>
        <key>name</key>
        <string>entity.name.tag.salt</string>
    </dict>

    <dict>
        <key>match</key>
        <string>%</string>
        <key>name</key>
        <string>keyword.operator.salt</string>
    </dict>

    <dict>
        <key>match</key>
        <string>\b(i8|i16|i32|i64|u8|u16|u32|u64|f32|f64|bool|void)\b</string>
        <key>name</key>
        <string>storage.type.salt</string>
    </dict>

    <dict>
        <key>match</key>
        <string>".*?"</string>
        <key>name</key>
        <string>string.quoted.double.salt</string>
    </dict>

    <dict>
        <key>match</key>
        <string>'.*?'</string>
        <key>name</key>
        <string>string.quoted.single.salt</string>
    </dict>

    <dict>
        <key>match</key>
        <string>//.*$</string>
        <key>name</key>
        <string>comment.line.salt</string>
    </dict>

    <dict>
        <key>match</key>
        <string>\b[0-9]+\b</string>
        <key>name</key>
        <string>constant.numeric.salt</string>
    </dict>

    <dict>
        <key>match</key>
        <string>\b(SUCCESS|FAILURE|true|false)\b</string>
        <key>name</key>
        <string>constant.language.salt</string>
    </dict>

</array>
</dict>
</plist>
